filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /app/logs/app.log

output.elasticsearch:
  hosts: ["https://elasticsearch:9200"]
  username: "elastic"
  password: "r_fV7lR2MyN+Jzcw-W-X"
  ssl.verification_mode: none
